/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pemesananhotel;

/**
 *
 * @author Lenovo
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        klikpelanggan = new javax.swing.JLabel();
        klikadmin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        klikpelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pemesananhotel/gambar/PELANGGAN.png"))); // NOI18N
        klikpelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                klikpelangganMouseClicked(evt);
            }
        });
        getContentPane().add(klikpelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, -1, -1));

        klikadmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pemesananhotel/gambar/ADMIN.png"))); // NOI18N
        klikadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                klikadminMouseClicked(evt);
            }
        });
        getContentPane().add(klikadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pemesananhotel/gambar/BACKGOUND LOGIN.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void klikadminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_klikadminMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
login_admin admin=new login_admin();
admin.setLocationRelativeTo(admin);
admin.setVisible(true);
    }//GEN-LAST:event_klikadminMouseClicked

    private void klikpelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_klikpelangganMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
login_user user=new login_user();
user.setLocationRelativeTo(user);
user.setVisible(true);
    }//GEN-LAST:event_klikpelangganMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel klikadmin;
    private javax.swing.JLabel klikpelanggan;
    // End of variables declaration//GEN-END:variables
}
